### ISSUE TITLE
Add-In could not be loaded - Exception caused by Hotkey.cs

### ISSUE THREAD

**Issue by Pitterling** [rubberduck-vba/Rubberduck#1309]
With the recent updates i get a System.Argument Exception: Must specify valid information for parsing in the string.

![image](https://cloud.githubusercontent.com/assets/4181164/14275183/18937540-fb16-11e5-8fee-04bc474193c1.png)

```
        private static Keys GetCombo(string key)
        {
            return (Keys)Enum.Parse(typeof(Keys), key.Trim('%', '^', '+')) // will break with special keys, e.g. {f12}
                   | (key.Contains("%") ? Keys.Alt : Keys.None)
                   | (key.Contains("^") ? Keys.Control : Keys.None)
                   | (key.Contains("+") ? Keys.Shift : Keys.None);
        }
```

**Comment by INOPIAE** [comment]
Is this realted to #1281?

**Comment by retailcoder** [comment]
Could be the issue with the settings not adding missing entries... do you still get that error if you delete the `rubberduck.config` file and let it be rebuilt at startup?

**Comment by Hosch250** [comment]
I think this is a duplicate of #1281

**Comment by Pitterling** [comment]
removing the config file, solved this issue ... sorry for double reporting ... bu now i receive this error

> ContextSwitchDeadlock occurred
> Message: Managed Debugging Assistant 'ContextSwitchDeadlock' has detected a problem in 'C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE'.
> Additional information: The CLR has been unable to transition from COM context 0xfc79c8 to COM context 0xfc7910 for 60 seconds. The thread that owns the destination context/apartment is most likely either doing a non pumping wait or processing a very long running operation without pumping Windows messages. This situation generally has a negative performance impact and may even lead to the application becoming non responsive or memory usage accumulating continually over time. To avoid this problem, all single threaded apartment (STA) threads should use pumping wait primitives (such as CoWaitForMultipleHandles) and routinely pump messages during long running operations.
>

**Comment by retailcoder** [comment]
oh, crap. crap crap crap. :fearful:

**Comment by retailcoder** [comment]
@Pitterling I've no repro on that error message, however if I start Excel *without having the VS debugger attached*, everything seems to hang when I bring up the VBE, which seems pretty consistent with a `ContextSwitchDeadlock` issue.

I've tracked it down to the `EventHook` hooks - the library is generating its own `hWnd` to hook things up, and I suspect that's the problem. It might need a way to be supplied with an "outside" `hWnd`.

I've submitted an issue on the EventHook repo: https://github.com/justcoding121/Windows-User-Action-Hook/issues/3

**Comment by justcoding121** [comment]
I just released a change, where it would [not create a message loop](https://github.com/justcoding121/Windows-User-Action-Hook/blob/master/EventHook/Helpers/SharedMessagePump.cs#L23) if it already exists. Give it a try if you can please. Further it would try to use the main window handle [if its available](https://github.com/justcoding121/Windows-User-Action-Hook/blob/master/EventHook/Helpers/SharedMessagePump.cs#L82).

**Comment by retailcoder** [comment]
@justcoding121 without a debugger attached, the app becomes sluggish, and if the host (VBE) is deactivated and then re-activated, both the host (VBE) and its host app (e.g. Excel) appear to freeze for a while.

The part I still don't get is that it works pretty much flawlessly with a debugger attached - I have both `MouseWatcher` and `KeyboardWatcher` listening for events, plus my own hotkey hook (doesn't work without the debugger) and I'm also subclassing the VBE MainWindow to attach/detach all hooks when it gets/loses focus.

Problem is that it's hard to tell whether the sluggishness is due to the hooks, or to things like #1311. We have lots of work on our plate to stabilize Rubberduck for next release...

**Comment by justcoding121** [comment]
Just made a change, indeed it was causing sluggishness I noted. Added test projects for WPF, WinForms and Console. Works fine. However I am not sure about VBE. One thing I want to know is if its actually creating message pump or not in VBE. Sorry for the disaster.

**Comment by justcoding121** [comment]
And the change I mentioned in my above comment is not reflected in github yet. It was down for a while.

**Comment by justcoding121** [comment]
It is [now.](https://github.com/justcoding121/Windows-User-Action-Hook/commit/1a0566919ed7f4e51ca46b8ec00042e4dbae5048)

**Comment by retailcoder** [comment]
@justcoding121 awesome! no problem BTW, the real disaster is on my end :smile: 

Thanks for updating your library!
