### ISSUE TITLE
1.4.3.0 Object Reference not set

### ISSUE THREAD

**Issue by RaymondWise** [rubberduck-vba/Rubberduck#2282]
Excel 2016 16.0.4432.1000 64bit - Windows 7
Official release 1.4.3.0

Excel runs fine, but when I try to open the VBE I get

> Rubberduck Add-In could not be loaded
> Object reference not set to an instance of an object.

Once I hit "OK" the VBE opens and the Add-in Manager shows Rubberduck as available with startup/loaded behavior.

Maybe I missed a duplicate bug in my search, but I can't seem to resolve this. I tried using 2.0.8 but that's an entirely different basket of bugs for me.

**Comment by Vogel612** [comment]
Hi there,

have you already seen the ["Installing" wiki page](https://github.com/rubberduck-vba/Rubberduck/wiki/Installing)? It has a special section for troubleshooting this exact error you have. 
Maybe this already solves your problem. If it doesn't please do tell us 👍

**Comment by RaymondWise** [comment]
@Vogel612  Thanks. I ran that and got the successful message, but I'm still getting the "object reference not set to an instance of an object" error.

**Comment by Vogel612** [comment]
You should be able to find the logs under `%AppData%/Rubberduck/logs`. At this point a Stacktrace would greatly help us nail the error down.

You'll find one either in the logs (most probably as the last few lines)  or in the details of the error message you get.

**Comment by retailcoder** [comment]
@Vogel612 IIRC v1.4.3 didn't have that logging feature in release. The NRE is probably one of the many bugs that were fixed between 1.4.3 and 2.x.

Is there an active codepane when the vbe launches?

**Comment by RaymondWise** [comment]
So I uninstalled RD, cleaned up the files, removed all the office 07/10/13 entries from the registry, ran all the 2016 updates. Restarted, installed RD as admin and got the error. Ran the cmd fix as admin again and still getting the error.

The `\AppData\Roaming\Rubberduck\Logs\RubberduckLog` has no entries for today. Yesterday only has repeated

> 
> 2016-10-04 13:11:11.0114;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBE;
> 2016-10-04 13:11:11.2504;WARN;Rubberduck.Parsing.Symbols.TypeAnnotationPass;Failed to resolve type VBProject;
> 2016-10-04 13:12:29.4169;ERROR;Rubberduck.Common.WinAPI.RawInput;Error sizing the rawinput buffer: The handle is invalid;System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
> 2016-10-04 13:15:35.7626;WARN;Rubberduck.Parsing.Symbols.IdentifierReferenceResolver;Default Context: Failed to resolve b. Binding as much as we can.;

No, no active modules when the VBE opens, just the standard panes and locals.

**Comment by retailcoder** [comment]
@RaymondWise there was a bug at one point (not sure which release fixed it) where RD wouldn't start without at least one project in `VBE.VBProjects`; since the bug is now fixed, I'll close this issue. Make sure there's a host document in the host application when you open up the VBE.

**Comment by RaymondWise** [comment]
@retailcoder Pardon my ignorance, but by host document do you mean ensure that excel starts with an .xlam (or) ensure it has a personal macro workbook enabled? I've just tried both of those and have had no luck. I can just migrate to the latest release if need be..
