### ISSUE TITLE
Source Control API: Error on CreateGitProvider

### ISSUE THREAD

**Issue by adamchaz** [rubberduck-vba/Rubberduck#3027]
Hello,
I'm using Excel 2016. When I use the Source Control API. I'm getting the following Error on CreateGitProvider. 

"Unable to cast object of Type 'System.__ComObject' to type 'Rubberduck.vbEditer.SafeComWrappers.VBA.VBProject"

**Comment by retailcoder** [comment]
Aah, we've fixed this error with the Rubberduck API, but seems we forgot the SC API. The COM wrappers introduced in 2.0.9 (or was it .10?) had broken the COM APIs.. That's an easy fix, but the SC API won't be usable until we ship a fix.

If you only want to use the SC API you can use a RD release prior to 2.0.9; that DLL hasn't changed since 1.4.3 AFAIK.

**Comment by adamchaz** [comment]
Thanks, 
I downloaded and installed 2.0.8. The CreateGitProvider is looking for a variable called wrapperfactory. That has an unknown type.

**Comment by rubberduck203** [comment]
@adamchaz do you need RD's other features, or are you just looking to use the SC API to write some software? 

If it's the later, I'd recommend v1.4.3, it's the last time that I know *for sure* that the COM API for Git worked.

**Comment by adamchaz** [comment]
Hello Thanks for your help. Still getting the same error in earlier versions.

**Comment by retailcoder** [comment]
@adamchaz `SafeComWrapper<T>` was *introduced* in 2.x; the error can't possibly be the same in 1.4.3.

**Comment by adamchaz** [comment]
uninstalled and attempted to unregister the 2.08 and install register 1.4.3. Is there any thing else that I need to do.

**Comment by rubberduck203** [comment]
Unfortunately we decided to remove the feature. #3758
