### ISSUE TITLE
Commit Failed: Configuration value 'user.name' is missing or invalid

### ISSUE THREAD

**Issue by tdmsoares** [rubberduck-vba/Rubberduck#3057]
![rubberduck_commitfailed](https://user-images.githubusercontent.com/13411645/26881636-66d6640c-4b6e-11e7-89d5-1e49a6a493a8.jpg)
Hello guys,

I'm using rubberduck and it's my first commit I want to do to my remote repository to github. I followed the instructions in Source Control: Get Started, so the Repository folder is already in my local computer, I added the files to commit, but when I click "Commit and Push", I get the message:

> Commit Failed: Configuration value 'user.name' is missing or invalid

How can I fix this problem, is something that I need to do, create a config file? 

Thanks

**Comment by retailcoder** [comment]
The configuration file is created automatically, under `%appdata%\Rubberduck\SourceControl.rubberduck`. It's an XML file that you can edit in notepad/notepad++. Verify that the `<UserName>` tag is correctly populated:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Configuration>
  <SourceControlSettings>
    <UserName />
    <EmailAddress />
    <DefaultRepositoryLocation />
    <Repositories>
      <Repository>
        <Id>96733338</Id>
        <LocalLocation>C:\Dev\VBTools\VBTools</LocalLocation>
        <RemoteLocation />
      </Repository>
    </Repositories>
    <CommandPromptLocation>cmd.exe</CommandPromptLocation>
  </SourceControlSettings>
</Configuration>
```

That said, the Source Control feature has a number of issues (as mentioned in the release notes) - always keep a backup copy of your VBA project, and use it at your own risk.

Also, the identifier `Form_Cadastro Circlo` seems to contain a whitespace, which would make it an illegal identifier; that's most likely why you're seeing that "Parse Error" message - this will likely interfere with source control, which exports/re-imports files from the project as it refreshes: one known issue in 2.0.13 (fixed now) is that it doesn't play nicely with paths containing whitespace.

**Comment by tdmsoares** [comment]
@retailcoder I opened the XML file and the values are as same as I set in Source Control Settings, the username is the correct one. But it's still not working...

**Comment by daFreeMan** [comment]
@tdmsoares maybe post your config file so the experts can take a look at it?

**Comment by rubberduck203** [comment]
If this is the first time you've ever used Git, you may need to set up your username and email. 

```
git config --global user.name="First Last"
git config --global user.email=first.last@domain.com
```

**Comment by michael-lark** [comment]
Rubberduck203 - your advice above was what I needed to fix the error message. I had to change the syntax of your post just slightly though to remove the equals sign:

git config --global user.name "First Last"
git config --global user.email first.last@domain.com

Before I did that, git config gave me an error message. I changed it based on the docs:
https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
