### ISSUE TITLE
Regex Search & Replace

### ISSUE THREAD

**Issue by retailcoder** [rubberduck-vba/Rubberduck#327]
Let's implement a regex search & replace functionality; a simple dialog that allows entering a regex pattern, selecting the scope of the search (current procedure, current component/module, current project, all opened code panes, or just _everywhere_); there needs to be "find next", "replace", "replace all" and "cancel" buttons.

**Comment by Hosch250** [comment]
Seeing as this is mostly implemented (although probably buggy), I'm moving this to 2.0.  I will look into fixing the UI and working on it later.

**Comment by retailcoder** [comment]
I had started the re-wiring of that feature into the 2.0 architecture, what's left to do is to move logic from the dockable presenter into a ViewModel (leaving the presenter pretty much empty), and make a nice XAML UserControl for it.

**Comment by ThunderFrame** [comment]
let's just tweak "replace all" and make it "replace all selected"

**Comment by SteveLaycock** [comment]
Could I give a little nudge for this feature.  I'm currently stuck with  non-compilable code so can't use Rubberduck's refactoring.  Find and replacing that allowed proper wildcards would be really really helpful right now.

**Comment by NDeLancie** [comment]
I endorse giving a nudge to this feature as the VBA IDE's Ctrl-H find and replace feature is woefully inadequate for doing anything except the simplest find and replace operations, and one should not have to copy code to an advanced text editor (such as UltraEdit), use its RegEx-based search and replace feature to edit that code, and then copy it back into the VBA IDE code window if RubberDuck is a "full-featured" IDE for VBA.

Also in this vein, the Refactor > Rename capability should support RegEx-based renaming and should also provide scoping for renaming to make it a truly exceptional feature.

**Comment by zspitz** [comment]
1. Hasn't this been implemented already? The linked PR seems to have been closed.
2. Is this / should it be implemented using .NET regular expressions? Or the VBScript regex engine, which AFAIK is the only regex engine available to VBA?

**Comment by NDeLancie** [comment]
Zev:  So far as I can find, no RegEx-based search and replace function has been implemented on any of the RD menus. If I missed it, my apologies.

The second part of my suggestion--related to the general one--re scoping and RegEx capabilities for Refactor > Rename--is also not implemented so far as I can tell.

All of this would be very useful.

**Comment by MDoerner** [comment]
There has been a first implementation of this feature for a long time. However, it has some serious issues, e.g. in its handling of COM wrappers, and is only present in debug builds. I think nobody has worked on it for several years.

**Comment by NDeLancie** [comment]
Thanks, Max. I hope someone gets back into it, but I know it would be beyond my capabilities to do so.

**Comment by mindflux** [comment]
Is this implementation broken? Running 2.5.2.6059 and when I try and bring up the regex search and replace, nothing occurs.

Windows 10 Pro 21H2 64-bit
Office 365 64-bit 16.0.15726.20188

**Comment by retailcoder** [comment]
Hm, that menu item shouldn't be there, this was on the back burner forever. On the bright side (?), it's definitely going to be a RD3 feature.

**Comment by daFreeMan** [comment]
@mindflux  you're a _couple_ of prereleases behind... You may want to upgrade to the latest build. A lot of things have been fixed in the last 10 months.

**Comment by mindflux** [comment]
> @mindflux you're a _couple_ of prereleases behind... You may want to upgrade to the latest build. A lot of things have been fixed in the last 10 months.

I downloaded what was latest on rubberduckvba.com. Where can I find something more recent?

**Comment by mindflux** [comment]
> @mindflux you're a _couple_ of prereleases behind... You may want to upgrade to the latest build. A lot of things have been fixed in the last 10 months.

Okay I grabbed what was latest on rubberduckba.  I've got a newer build off github loaded now.

**Comment by mindflux** [comment]
Running 2.5.2.6207 the Regex menu item still exists (it sounds like it's not supposed to right now?).

**Comment by pflugs30** [comment]
@NDeLancie Thanks for your detailed thoughts and ideas.  We appreciate your time.

It looks like your pictures didn't upload correctly, perhaps due to (what looks like) an email reply instead of using the Github website?  Either way, I like your ideas, and I'd like to see more of what you implemented.

May I suggest you create a new item in [the Ideas Discussions section](https://github.com/rubberduck-vba/Rubberduck/discussions/categories/ideas)?  This thread is about a different topic, and I wouldn't want your idea to be lost in the shuffle.  Thanks again!

**Comment by retailcoder** [comment]
This feature would technically still be in scope for 2.x, but will realistically not happen.
