### ISSUE TITLE
Code Explorer not updating with new '@Folder comments

### ISSUE THREAD

**Issue by Greedquest** [rubberduck-vba/Rubberduck#3704]
When adding `'@Folder` comments to modules and hitting refresh on the Code Explorer, I've been getting no changes to the folder layout

However a full re-parse seems to pick up the comments (when I close and re-open Excel). My code is too complicated to work out how to reproduce the problem, I can produce a similar one with the steps below. So perhaps my code has a similar problem.

## Reproduce ( a similar but not identical problem):

 - Open a new instance of Excel , add a new module , add a routine to it
```
Sub DoStuff()
End Sub
```
 - Turn on the Rubberduck Code Explorer, and hit parse
 - Add `'@Folder("folder1")` immediately above `Sub DoStuff` and reparse again
 - Code explorer does not update

My guess was that the hash function outlined in the [parsing process page][1] was not taking comments into account, but if I just add folder definitions to the modules (no code, or only `Option Explicit`), then the code explorer does update. So the hash is sensitive to changes in comments.

Also, adding `Debug.Print "stuff"` to my `Do stuff()` Sub - which should _definitely_ mark the module as changed to Rubberduck - still does not cause the `'@Folder` annotation to be spotted. Unlike in my actual code, re-opening Excel and fully re-parsing does not solve this, but adding a line break after `'@Folder("folder1")` does.

## Possible Fix

Add an option to force complete re-parse. I'm aware that this is disabled by design, but it seems like a much better alternative than re-opening Excel completely. Otherwise, is there a set format I should follow with my comments (should they be at the top of the module, not adjacent to other lines etc.?)

  [1]: http://(https://github.com/rubberduck-vba/Rubberduck/wiki/The-Parsing-Process#doing-only-what-is-necessary)

**Comment by Greedquest** [comment]
Just looked, I'm getting a lot of `Annotation 'Folder' is illegal in this context` errors (see image), some of which can be solved by moving the annotation to the first line of the module. Others like the example in the image (where the module is in the wrong folder) still give the error, and still won't update the Code Explorer, except on opening/closing the workbook.

[![error messages][1]][1]


  [1]: https://i.stack.imgur.com/GVAO5.png

**Comment by Vogel612** [comment]
Re: the first repro steps: 

You'll need to have at least an empty line between the folder annotation and the Sub  like so:

```
'@Folder("Tests")

Public Sub DoStuff()
End Sub
```

the VBE should then draw a demarcation line below the comment to mark the end of the module header.
Folder annotations are only parsed correctly in the Module Header.

The second repro seems worrying, it should work in that case, the first is [status-by-design] though. Because there's no empty line between the annotation and the Sub, the annotation is considered as annotating the Sub (which is illegal for `@Folder`. 

Could you try to include `Option Explicit` below the `@Folder` annotation in your second repro to see whether that "fixes" the problem? Thanks.

**Comment by Greedquest** [comment]
Adding `Option Explicit` below, below with a space, above or above with a space all leave the same error message, and also fail to update the Code Explorer

Rubberduck v. 2.1.0.10753
Windows v.10.0.16299 Build 16299
Office v.1711 Build 8730.2165 Click-to-Run

**Comment by retailcoder** [comment]
@Greedquest note that this issue has been fixed already; we haven't "green-released" v2.2 yet because we're currently working on putting the final few nails on the teardown issues' coffin, but feel free to upgrade to the latest pretelease build.

Ref. PR #3524, issue #3393

**Comment by retailcoder** [comment]
Hmm, something isn't quite adding up. Needs investigation.

**Comment by retailcoder** [comment]
Just to confirm, there's no parser error and the inspection results are up-to-date?

**Comment by Greedquest** [comment]
Yes, the parsing all went smoothly, and as I say, when I do a full parse (close and open the file then re-parse) the folders in Code Explorer work as expected. But the inspection errors are still there, and updating the `'@Folder` argument then re-parsing doesn't change the folder structure any more.

**Comment by Vogel612** [comment]
I cannot reproduce this issue from `next`. My "Illegal Annotation Inspection" severity is set to "Error", but I don't see any inspection results, even though I have at least one illegal annotation there. Soo ... something's fishy, but the other way round

**Comment by Greedquest** [comment]
If you want to look at the workbook that caused it, there it is. The `MultiThreadTests` module was definitely acting strangely
[MultiThreadRubberduck.zip](https://github.com/rubberduck-vba/Rubberduck/files/1636004/MultiThreadRubberduck.zip)

**Comment by comintern** [comment]
This appears to work correctly with the current build.

**Comment by Vogel612** [comment]
This has probably been fixed with #4648
