### ISSUE TITLE
False Positives for Builtin Functions and Constants

### ISSUE THREAD

**Issue by carlossierra311** [rubberduck-vba/Rubberduck#4174]
I am getting close to 200 Code Quality Issues for things like constants and built-in functions. As an example, see the following image:
![falsepositives](https://user-images.githubusercontent.com/23511373/42583883-89aaf538-84f7-11e8-8dec-0438fa51d415.png)

The MsgBox line alone generates 6 issues (the 3 shown in the image, plus 3 more further down the issues list for those same "variables" not being assigned). 

Other variables and functions that generate issues are: Err, xlUp, xlToLeft, InStr, Dir, IsNumeric, etc. 

As a seemingly related symptom of the same underlying problem, functions like CDbl, CStr, RGB are also identified as variables, generating the same Code Quality Issues than the above, but they also get listed in the Maintainability and Readability Issues section for their names being too short. The suggestion is to rename them :(

Please let me know if you need further details about it. 

Thanks! 

Version 2.2.6737.8365
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.10228.20080
Host Executable: EXCEL.EXE

**Comment by retailcoder** [comment]
I bet the initial parse took much longer than usual, and that the logs (if enabled) contain exceptions involving the COM collector, saying something to the effect of "type library 'VBA' could not be loaded"... this has been a problem relatively recently, but it seems to have been fixed.

Is this a debug build? The mismatching version numbers bug (splash screen vs about box showing different version numbers) was fixed relatively recently; does the current/latest pre-release build have the same problem?

**Comment by carlossierra311** [comment]
No, parsing didn't take a particullarily long time. 
I'll try the latest pre-release and let you know if the issues are fixed there.

**Comment by carlossierra311** [comment]
I just downloaded the [latest release](https://github.com/rubberduck-vba/Rubberduck/releases/download/Rubberduck-v2.2.0.3468/Rubberduck.Setup.2.2.0.3468-pre.exe) and the problem persists. 

Version 2.2.0.3468
OS: Microsoft Windows NT 10.0.17134.0, x64
Host Product: Microsoft Office 2016 x86
Host Version: 16.0.10228.20080
Host Executable: EXCEL.EXE

[RubberduckLog.txt](https://github.com/rubberduck-vba/Rubberduck/files/2186128/RubberduckLog.txt)

**Comment by comintern** [comment]
Closing against #4181.
